'use strict';

/**
 * Full pool mapping (all FORMATION + BOARD players from site/index.html)
 * to what the tweet-feed needs: position (for template selection), a
 * short club name (for the stat-line header), and a provider player ID
 * to fill in once a real stats provider is wired up (see CLAUDE.md "Data
 * vendor decisions").
 *
 * GENERATED by scripts/generate_pool_config.js - do not hand-edit. Run
 * that script again after any FORMATION/BOARD change in site/index.html
 * instead of patching this file directly; hand-syncing it drifted stale
 * three times before this generator existed (see docs/agent-handoff.md,
 * 2026-09-26 entry, for what that looked like: wrong starters vs. depth,
 * players in the wrong section, a stale count in this very comment).
 *
 * Current count: 28 FORMATION + 20 BOARD = 48 total.
 */
const POOL = [
  // --- FORMATION: starters ---
  { name: 'Okoye', fullName: 'Maduka Okoye', shortClub: 'Udinese', position: 'GK', providerPlayerId: null },
  { name: 'Aina', fullName: 'Ola Aina', shortClub: 'Nottingham Forest', position: 'DEF', providerPlayerId: null },
  { name: 'Bassey', fullName: 'Calvin Bassey', shortClub: 'Fulham', position: 'DEF', providerPlayerId: null },
  { name: 'Ahanor', fullName: 'Honest Ahanor', shortClub: 'Crystal Palace', position: 'DEF', providerPlayerId: null },
  { name: 'Sanusi', fullName: 'Zaidu Sanusi', shortClub: 'Porto', position: 'DEF', providerPlayerId: null },
  { name: 'Nwaneri', fullName: 'Ethan Nwaneri', shortClub: 'Marseille', position: 'MID', providerPlayerId: null },
  { name: 'Onyeka', fullName: 'Frank Onyeka', shortClub: 'Coventry City', position: 'MID', providerPlayerId: null },
  { name: 'Onyedika', fullName: 'Raphael Onyedika', shortClub: 'Eintracht Frankfurt', position: 'MID', providerPlayerId: null },
  { name: 'Ngumoha', fullName: 'Rio Ngumoha', shortClub: 'Liverpool', position: 'MID', providerPlayerId: null },
  { name: 'Osimhen', fullName: 'Victor Osimhen', shortClub: 'Gala', position: 'FWD', providerPlayerId: null },
  { name: 'Lookman', fullName: 'Ademola Lookman', shortClub: 'Atleti', position: 'FWD', providerPlayerId: null },

  // --- FORMATION: reserves (depth) ---
  { name: 'Nwabali', fullName: 'Stanley Nwabali', shortClub: 'Chippa', position: 'GK', providerPlayerId: null },
  { name: 'S. James', fullName: 'Samuel James', shortClub: 'SJK', position: 'GK', providerPlayerId: null },
  { name: 'Osayi-Samuel', fullName: 'Bright Osayi-Samuel', shortClub: 'Birmingham City', position: 'DEF', providerPlayerId: null },
  { name: 'Ndukwe', fullName: 'Ifeanyi Ndukwe', shortClub: 'Levante', position: 'DEF', providerPlayerId: null },
  { name: 'Adarabioyo', fullName: 'Tosin Adarabioyo', shortClub: 'Chelsea', position: 'DEF', providerPlayerId: null },
  { name: 'Fredrick', fullName: 'Benjamin Fredrick', shortClub: 'FCV Dender EH', position: 'DEF', providerPlayerId: null },
  { name: 'Ajayi', fullName: 'Semi Ajayi', shortClub: 'Hull City', position: 'DEF', providerPlayerId: null },
  { name: 'Iwobi', fullName: 'Alex Iwobi', shortClub: 'Fulham', position: 'MID', providerPlayerId: null },
  { name: 'Ndidi', fullName: 'Wilfred Ndidi', shortClub: 'Besiktas', position: 'MID', providerPlayerId: null },
  { name: 'Ugochukwu', fullName: 'Lesley Ugochukwu', shortClub: 'Gala', position: 'MID', providerPlayerId: null },
  { name: 'Chukwueze', fullName: 'Samuel Chukwueze', shortClub: 'AC Milan', position: 'MID', providerPlayerId: null },
  { name: 'Simon', fullName: 'Moses Simon', shortClub: 'Paris FC', position: 'MID', providerPlayerId: null },
  { name: 'Awoniyi', fullName: 'Taiwo Awoniyi', shortClub: 'Coventry City', position: 'FWD', providerPlayerId: null },
  { name: 'Ekhator', fullName: 'Jeff Ekhator', shortClub: 'Juventus', position: 'FWD', providerPlayerId: null },
  { name: 'Adams', fullName: 'Akor Adams', shortClub: 'Venezia', position: 'FWD', providerPlayerId: null },
  { name: 'Arokodare', fullName: 'Tolu Arokodare', shortClub: 'Ajax', position: 'FWD', providerPlayerId: null },
  { name: 'Orban', fullName: 'Gift Orban', shortClub: 'Amedspor', position: 'FWD', providerPlayerId: null },

  // --- BOARD (20 entries - see site/index.html for current ranks, not fixed) ---
  { name: 'Oyebade', fullName: 'Rayan Oyebade', shortClub: 'West Ham', position: 'DEF', providerPlayerId: null },
  { name: 'Adeniran', fullName: 'Samuel Adeniran', shortClub: 'LASK', position: 'FWD', providerPlayerId: null },
  { name: 'Nwaiwu', fullName: 'Chibuike Nwaiwu', shortClub: 'Trabzonspor', position: 'DEF', providerPlayerId: null },
  { name: 'George', fullName: 'Tyrique George', shortClub: 'Everton', position: 'FWD', providerPlayerId: null },
  { name: 'Ezenwata', fullName: 'Chizzy Ezenwata', shortClub: 'Chelsea', position: 'FWD', providerPlayerId: null },
  { name: 'Troost-Ekong', fullName: 'William Troost-Ekong', shortClub: 'Besiktas', position: 'DEF', providerPlayerId: null },
  { name: 'Ozoh', fullName: 'David Ozoh', shortClub: 'Derby County', position: 'MID', providerPlayerId: null },
  { name: 'Etebo', fullName: 'Peter Etebo', shortClub: 'Genclerbirligi', position: 'MID', providerPlayerId: null },
  { name: 'Iheanacho', fullName: 'Kelechi Iheanacho', shortClub: 'Bursaspor', position: 'FWD', providerPlayerId: null },
  { name: 'Adewumi', fullName: 'Oluwaseun Adewumi', shortClub: 'Hertha BSC', position: 'MID', providerPlayerId: null },
  { name: 'I. James', fullName: 'Isaac James', shortClub: 'Alverca', position: 'DEF', providerPlayerId: null },
  { name: 'Ilenikhena', fullName: 'George Ilenikhena', shortClub: 'Al-Ittihad', position: 'FWD', providerPlayerId: null },
  { name: 'Usor', fullName: 'Moses Usor', shortClub: 'LASK', position: 'FWD', providerPlayerId: null },
  { name: 'Adiele', fullName: 'Emeka Adiele', shortClub: 'FC Utrecht', position: 'DEF', providerPlayerId: null },
  { name: 'Akpe', fullName: 'Victory Akpe', shortClub: 'FC Basel', position: 'DEF', providerPlayerId: null },
  { name: 'Bewene', fullName: 'Abdullahi Bewene', shortClub: 'Banik Ostrava', position: 'DEF', providerPlayerId: null },
  { name: 'Yohanna', fullName: 'Zadok Yohanna', shortClub: 'Brighton & Hove Albion', position: 'FWD', providerPlayerId: null },
  { name: 'Emenalo', fullName: 'Landon Emenalo', shortClub: 'Celtic', position: 'DEF', providerPlayerId: null },
  { name: 'E. Ekong', fullName: 'Emmanuel Ekong', shortClub: 'Malmo FF', position: 'FWD', providerPlayerId: null },
  { name: 'S. Ekong', fullName: 'Shalom Ekong', shortClub: 'GAIS', position: 'FWD', providerPlayerId: null },
];

module.exports = { POOL };
